version: "3.7"

services: 
    app:
        container_name: vite-template
        image: template
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            - 8080:8080